import UserPanelLayout from "@/components/Layouts/UserPanelLayout";
import ModalProvider from "@/components/Providers/ModalProvider";
import ThemeProvider from "@/components/Providers/ThemeProvider";
import { exo2, firaSansCondensed, signika } from "@/lib/fonts";
import type { Metadata } from "next";
import "./globals.css";

// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

export const metadata: Metadata = {
  title: "Arif's Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/logo-dark.svg",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/logo.svg",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${signika} ${exo2} ${firaSansCondensed} overflow-x-hidden`}
      >
        <ThemeProvider>
          <UserPanelLayout>
            <ModalProvider />
            {children}
          </UserPanelLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
